server:
  port: 3344

spring:
  application:
    name: cloud-config-center  # 注册进eureka Server 的微服务名
  cloud:
    config:
      server:
        git:
          skipSslValidation: true # 跳过ssl认证
          uri: https://github.com/Ahang-cloud/springcloud-config # github 仓库位置
          ## 搜索目录
          search-paths:
            - springcloud-config
          # 读取的分支
          label: master
  # rabbitMq的相关配置
  rabbitmq:
    host: localhost
    port: 5672  # 这里没错，5672是访问服务端口（随意），rabbitMQ网页端口是 15672
    username: guest
    password: guest
  # rabbitmq 的相关配置2 暴露bus刷新配置的端点
  management:
    endpoints:
      web:
        exposure:
          include: 'bus-refresh'

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/