server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  ## GateWay配置
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh1 # 路由ID，没有固定的规则，但要求唯一，建议配合服务名
          # uri: http://localhost:8001  # 匹配后提供服务的路由地址
          uri: lb://cloud-provider-payment # 使用服务名
          predicates:
            - Path=/payment/findById/**  # 断言，路径相匹配的进行路由

        - id: payment_routh2 # 路由ID，没有固定的规则，但要求唯一，建议配合服务名
          # uri: http://localhost:8001  # 匹配后提供服务的路由地址
          uri: lb://cloud-provider-payment # 使用服务名
          predicates:
            - Path=/payment/lb/** # 断言，路径相匹配的进行路由

# uri: lb://CLOUD-PROVIDER-SERVICE  解释：lb 属于GateWay 的关键字，代表是动态uri，即代表使用的是服务注册中心的微服务名，它默认开启使用负载均衡机制

# 注册进 eureka Server
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
    register-with-eureka: true
    fetch-registry: true
