server:
  port: 8001

spring:
  application:
    name: cloud-hystrix-provider-payment

eureka:
  client:
    # 注册进 Eureka 的服务中心
    register-with-eureka: true
    # 检索 服务中心 的其它服务
    fetch-registry: true
    service-url:
      # 设置与 Eureka Server 交互的地址
      #defaultZone: http://localhost:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: payment8001   #注册中心实例的名字
    prefer-ip-address: true   #是否显示实例的 IP以及端口号信息（鼠标悬浮）