server:
  port: 80

spring:
  application:
    name: cloud-feign-hystrix-consumer

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/ # 入驻地址
  instance:
    instance-id: feignHystrixOrder80
    prefer-ip-address: true

# 设置 Openfeign 客户端超时时间，默认超时等待1秒
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000

# 用于服务降级 在注解@FeignClient 中添加 fallback 属性值
feign:
  hystrix:
    enabled: true  # 在feign中开启 hystrix