server:
  port: 83
spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos的服务地址
management: # 服务信息暴露
  endpoints:
    web:
      exposure:
        include: '*'

# 激活Sentinel对Feign的支持
feign:
  sentinel:
    enabled: true

# 自定义配置，方便 @Value 注解读取
server-url:
  nacos-user-service: http://nacos-provider # nacos 中某个服务的名称